# Generated by Django 3.0.4 on 2020-04-02 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=10)),
                ('address_line1', models.CharField(max_length=20)),
                ('address_line2', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=10)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('map_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.IntegerField()),
                ('sub_category', models.IntegerField()),
                ('main_category_desc', models.CharField(max_length=50)),
                ('sub_category_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='conference',
            fields=[
                ('conf_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('main_category', models.IntegerField()),
                ('sub_category', models.IntegerField()),
                ('conf_ownerId', models.IntegerField()),
                ('paper_Accepted', models.IntegerField()),
                ('conf_deadline', models.DateField()),
                ('description', models.TextField()),
                ('about', models.TextField()),
                ('conf_Submission_date', models.DateField()),
                ('conf_start_date', models.DateField()),
                ('conf_end_date', models.DateField()),
                ('conf_loc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.address')),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('role', models.CharField(max_length=40)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.address')),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='conference_itemTable',
            fields=[
                ('paper_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('1', 'Abstract Not Submitted'), ('2', 'Abstract Submitted'), ('3', 'Reviewer Assigned'), ('4', 'Review In Progress'), ('5', 'Abstract Accepted'), ('6', 'Abstract Rejected'), ('7', 'Paper Submitted')], default='1', max_length=1)),
                ('reviewer1_id', models.IntegerField()),
                ('reviewer2_id', models.IntegerField()),
                ('reviewer1_status', models.CharField(max_length=20)),
                ('reviewer2_status', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('pdf_link', models.CharField(max_length=50)),
                ('conf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.conference')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('paper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.conference_itemTable')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.user_table')),
            ],
        ),
    ]
