# Generated by Django 3.0.4 on 2020-04-11 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=30)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('address_line1', models.CharField(blank=True, max_length=50)),
                ('address_line2', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(max_length=30)),
                ('phone', models.BigIntegerField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('map_link', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.IntegerField()),
                ('sub_category', models.IntegerField()),
                ('main_category_desc', models.CharField(max_length=50)),
                ('sub_category_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='conference',
            fields=[
                ('conf_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('main_category', models.IntegerField()),
                ('sub_category', models.IntegerField()),
                ('conf_ownerId', models.IntegerField()),
                ('paper_Accepted', models.IntegerField(blank=True)),
                ('conf_deadline', models.DateField()),
                ('description', models.TextField()),
                ('about', models.TextField()),
                ('conf_Submission_date', models.DateField()),
                ('conf_start_date', models.DateField()),
                ('conf_end_date', models.DateField(blank=True)),
                ('conf_loc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.address')),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('skill_category', models.IntegerField(blank=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='conference_itemTable',
            fields=[
                ('paper_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('1', 'Abstract Not Submitted'), ('2', 'Abstract Submitted'), ('3', 'Reviewer Assigned'), ('4', 'Review In Progress'), ('5', 'Abstract Accepted'), ('6', 'Abstract Rejected'), ('7', 'Paper Submitted')], default='1', max_length=1)),
                ('reviewer1_id', models.IntegerField(blank=True)),
                ('reviewer2_id', models.IntegerField(blank=True)),
                ('reviewer1_status', models.CharField(blank=True, max_length=20)),
                ('reviewer2_status', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField()),
                ('pdf_link', models.CharField(blank=True, max_length=50)),
                ('entry_date', models.DateField(blank=True)),
                ('conf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.conference')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('paper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.conference_itemTable')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
